name: GitHub Script Action demo 
on: 
  workflow_dispatch:

jobs:
  reading-step-results: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Write a string in script
        id: write-a-string-in-script
        uses: actions/github-script@v7.0.1
        with:
          script: | 
            return "Hello!"; 
          result-encoding: string 
      - name: Get result 
        run: echo "${{ steps.write-a-string-in-script.outputs.result }}"
