# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
name: Publish And Run Docker Image With Direct Usage of Command  

on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: Log level
        required: true 
        default: 'warning'
      tags: 
        description: Test scenario tags 
        
permissions:
  packages: write
  contents: read
  
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setting up Docker metadata
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/publish-packages/game
          tags: type=sha
      
      # Login to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY }}
      
      # Build the Docker image
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  run:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      # Login to GHCR
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY }}
          
      # Pull the Docker image
      - name: Pull Docker image
        run: docker pull ${{ needs.publish.outputs.image_tag }}
      
      # Run the Docker container
      - name: Run Docker container
        run: docker run -d --name my-container -p 8080:80 ${{ needs.publish.outputs.image_tag }}
      
      # Display container logs
      - name: Display container logs
        run: docker logs my-container
