# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
name: Fail Fast and Continue on Error 
on:
  workflow_dispatch: 

jobs:
  demo: 
    runs-on: ubuntu-latest 
    # You can use jobs.<job_id>.strategy.fail-fast and jobs.<job_id>.continue-on-error together.  
    # 
    # If any of the jobs with continue-on-error: false fail, all jobs that are in progress or queued will be cancelled. 
    # If the job with continue-on-error: true fails, the other jobs will not be affected.
    continue-on-error: ${{ matrix.coe-flag }}
    strategy:
      fail-fast: true
      matrix:
        version: [6, 7, 8]
        coe-flag: [false] 
        include: 
          - version: 9
            coe-flag: true 
    steps:
      - name: Run demo
        run: |
          echo "Running tests for version ${{ matrix.version }}"
          if [ ${{ matrix.version }} -eq 9 ]; then
            echo "Simulating failure for version 9"
            exit 1
          else
            echo "Simulating success for version ${{ matrix.version }}"
            exit 0
          fi
