# https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
name: Create a Javascript action 
on: 
  workflow_dispatch:

jobs:
  use-custom-action:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v4.1.5
      - name: Use a custom action 
        id: use-a-custom-action
        uses: ./.github/actions/doc_javascript_action@v1.1 
        with:
          who-to-greet: 'Hello GitHub Actions!'
      - name: Get a custom action output 
        run: echo "The greeting time was ${{ steps.use-a-custom-action.outputs.time }}"
