# https://docs.github.com/en/actions/learn-github-actions/essential-features-of-github-actions#adding-scripts-to-your-workflow
#
# 워크플로에서 실행할 스크립트의 위치를 지정하여, 기본 작업 디렉토리를 설정할 수 있습니다.
name: Add scripts to your workflow 
on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: Log level
        required: true 
        default: 'warning'
      tags: 
        description: Test scenario tags 

jobs:
  perform-on-added-scripts:
    runs-on: ubuntu-latest
    # 작업의 기본값 설정 (https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs)
    defaults: 
      run:
        shell: bash 
        working-directory: ./scripts 
    steps:
      # 리포지토리에 저장된 스크립트를 실행하기 위해서는 먼저 리포지토리를 러너에 체크아웃해야 합니다.
      - name: Checkout
        uses: actions/checkout@v4.1.5
      # 워크플로 작업이 실행할 모든 스크립트는 실행 가능해야 합니다. (execution 권한 설정 필요) 
      # 다음 step을 실행하거나 또는 `git update-index --chmod=+x PATH/TO/YOUR/script.sh` 명령을 로컬에서 실행하고 리포지토리에 푸시합니다.  
      - name: Make the script executable 
        run: chmod +x ./hello_github.sh
      # 로드된 스크립트를 실행합니다.
      - name: Run the loaded script 
        run: ./hello_github.sh
