# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
name: Publish And Run Docker Image With Container Option 

on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: Log level
        required: true 
        default: 'warning'
      tags: 
        description: Test scenario tags 
        
permissions:
  packages: write
  contents: read
  
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/publish-packages/game
          tags: type=sha
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_REGISTRY }}
      
      - name: Build container
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: Image tag print 
        run: echo "${{ steps.meta.outputs.tags }}"
  
  # `container` 옵션 사용을 통한 이미지 실행  
  run:
    runs-on: ubuntu-latest
    needs: publish
    container:
      image: ${{ needs.publish.outputs.image_tag }}
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Display container logs
        run: python /app/hello.py
