name: Label and Comment Issues

on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_and_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add labels to issue
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          # Separate multiple labels with commas without space.
          # Add the `documentation`, `good first issue` labels every time an issue is opened or reopened. 
          LABELS: documentation,good first issue

      - name: Add comment to issue
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          BODY: |
            This issue is available for anyone to work on.
            **Make sure to reference this issue in your pull request.**
            :sparkles: Thank you for your contribution! :sparkles:
