# 이 워크플로우는 Node.js 의존성을 설치하고, 캐시/복원하며, 소스 코드를 빌드한 후, 빌드 결과물을 아티팩트로 업로드하고 이를 테스트 단계에서 다운로드합니다.
# 
# 아티팩트(Artifacts)는 로그 항목 이외의 워크플로우에서 생성된 파일(예: node_modules 등 빌드 시 생성되는 모듈 파일)들을 의미합니다.
# 아티팩트 업로드/다운로드 기능을 활용하여 빌드 또는 테스트 결과물 등을 다른 작업(job)에서 사용하거나 디버깅/테스트를 수행할 수 있습니다. 
name: Artifacts Demo 

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        
    steps:
      - uses: actions/checkout@v4.1.5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: npm install and build webpack 
        run: |
          npm install 
          npm run build 
      # 빌드 시 발생 artifacts 업로드 
      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts 
          path: node_modules/ 

  test:
    needs: build 
    runs-on: ubuntu-latest 
    steps:
      # 이전 수행된 작업에서 업로드된 artifacts를 현재 작업에서 다운로드 
      - uses: actions/checkout@v4.1.5
      - uses: actions/download-artifact@v4.1.7
        with:
          name: webpack artifacts 
          path: node_modules 

## Build continuous integration (CI) workflows by using GitHub Actions > Customize your workflow with environment variables and artifact data
## https://learn.microsoft.com/en-us/training/modules/github-actions-ci/2b-github-actions-essential-features
