name: Notify Teams over GitHub events

on:
  push:
    branches:
      - main

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Commit Information
        id: commit_info
        run: |
          echo "MESSAGE=${{ github.event.head_commit.message }}" >> $GITHUB_ENV
          echo "AUTHOR=${{ github.actor }}" >> $GITHUB_ENV
          echo "BRANCH=${{ github.ref }}" >> $GITHUB_ENV
          echo "COMMIT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Send Notification
        run: |
          curl -X POST -H 'Content-type: application/json' -d "{
            \"text\": \"New commit pushed to branch: ${{ env.BRANCH }}\",
            \"sections\": [
              {
                \"activityTitle\": \"Commit Information\",
                \"activitySubtitle\": \"Message: \",
                \"activityText\": \"${{ env.MESSAGE }}\",
                \"facts\": [
                  {
                    \"name\": \"Author\",
                    \"value\": \"${{ env.AUTHOR }}\"
                  },
                  {
                    \"name\": \"Branch\",
                    \"value\": \"${{ env.BRANCH }}\"
                  },
                  {
                    \"name\": \"Commit URL\",
                    \"value\": \"[${{ env.COMMIT_URL }}](${{ env.COMMIT_URL }})\"
                  }
                ]
              }
            ]
          }" "${{ secrets.TEAMS_WEB_HOOK_URL }}"
