name: Notify Teams over GitHub events

on:
  push:
    branches:
      - main

jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Commit Information
        id: commit_info
        run: |
          echo "MESSAGE=$(git log -1 --pretty=format:%s)" >> $GITHUB_ENV
          echo "AUTHOR=$(git log -1 --pretty=format:%an)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "COMMIT_URL=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Send Notification
        run: |
          curl -X POST -H 'Content-type: application/json' -d "{
            \"text\": \"New commit pushed to branch: ${{ env.BRANCH }}\",
            \"sections\": [
              {
                \"activityTitle\": \"Commit Information\",
                \"activitySubtitle\": \"Message: \",
                \"activityText\": \"${{ env.MESSAGE }}\",
                \"facts\": [
                  {
                    \"name\": \"Author\",
                    \"value\": \"${{ env.AUTHOR }}\"
                  },
                  {
                    \"name\": \"Branch\",
                    \"value\": \"${{ env.BRANCH }}\"
                  },
                  {
                    \"name\": \"Commit URL\",
                    \"value\": \"[${{ env.COMMIT_URL }}](${{ env.COMMIT_URL }})\"
                  }
                ]
              }
            ]
          }" "${{ secrets.TEAMS_WEB_HOOK_URL }}"
